print("How old are you?", end=' ')
age=input(38)
print("How tall are you?", end=' ')
height=input(120)
print("How much do you weight?", end=' ')
weight= input(129)
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
