from sys import argv
script, filename=argv
print(f"we're going to erase {filename}.")
print("If you don't want that, hit CIRL-C (^C).")
print("If you do want that, hit RETURN.")
input("?")
print("Oening the file...")
target=open(filename, 'w')
print("truncating the file. Goodbye!")
taget.truncate()
print("now I'm going to ask you for three lines.")
line1=input("line 1: ")
line2=input("line 2: ")
line3=input("line 3: ")
print("I'm goung to write these to the file.")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")
print("And finally, we close it.")
target.close()
